export function htmlTagRemover(str: string) {
  return str.replace(/(<([^>]+)>)/gi, "");
}

export function convertTimestamp(timestamp: any) {
  let date = timestamp.toDate();
  let mm = date.toLocaleString("default", { month: "short" });
  let dd = date.getDate();
  let EE = date.getDate();
  let yyyy = date.getFullYear();

  date = mm + " " + dd + ", " + yyyy;
  return date;
}

export function escapeBackticks(inputString: string) {
  return inputString.replace(/`/g, "\\`");
}

export function getRandomNumberInRange(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export function removeUndefinedValues(obj: { [key: string]: any }): {
  [key: string]: any;
} {
  const filteredObject: any = {};
  if (!obj) return filteredObject;
  for (const [key, value] of Object.entries(obj)) {
    if (value !== undefined) {
      filteredObject[key] = value;
    }
  }
  return filteredObject;
}

export function checkColorBrightness(c: string) {
  var c = c.substring(1); // strip #
  var rgb = parseInt(c, 16); // convert rrggbb to decimal
  var r = (rgb >> 16) & 0xff; // extract red
  var g = (rgb >> 8) & 0xff; // extract green
  var b = (rgb >> 0) & 0xff; // extract blue

  var luma = 0.2126 * r + 0.7152 * g + 0.0722 * b;

  //if luma is less than 40 it's dark
  //if greater than 128 it;s light
  if (luma > 200) {
    return "black";
  } else if (luma < 201) {
    return "white";
  }
}

export const countriesISOList: string[] = [
  "Afghanistan (AF)",
  "Albania (AL)",
  "Algeria (DZ)",
  "Andorra (AD)",
  "Angola (AO)",
  "Antigua and Barbuda (AG)",
  "Argentina (AR)",
  "Armenia (AM)",
  "Australia (AU)",
  "Austria (AT)",
  "Azerbaijan (AZ)",
  "Bahamas (BS)",
  "Bahrain (BH)",
  "Bangladesh (BD)",
  "Barbados (BB)",
  "Belarus (BY)",
  "Belgium (BE)",
  "Belize (BZ)",
  "Benin (BJ)",
  "Bhutan (BT)",
  "Bolivia (BO)",
  "Bosnia and Herzegovina (BA)",
  "Botswana (BW)",
  "Brazil (BR)",
  "Brunei (BN)",
  "Bulgaria (BG)",
  "Burkina Faso (BF)",
  "Burundi (BI)",
  "Cabo Verde (CV)",
  "Cambodia (KH)",
  "Cameroon (CM)",
  "Canada (CA)",
  "Cape Verde (CV)",
  "Central African Republic (CF)",
  "Chad (TD)",
  "Chile (CL)",
  "China (CN)",
  "Colombia (CO)",
  "Comoros (KM)",
  "Congo (CG)",
  "Congo (Democratic Republic) (CD)",
  "Costa Rica (CR)",
  "Croatia (HR)",
  "Cuba (CU)",
  "Cyprus (CY)",
  "Czech Republic (CZ)",
  "Denmark (DK)",
  "Djibouti (DJ)",
  "Dominica (DM)",
  "Dominican Republic (DO)",
  "Ecuador (EC)",
  "Egypt (EG)",
  "El Salvador (SV)",
  "Equatorial Guinea (GQ)",
  "Eritrea (ER)",
  "Estonia (EE)",
  "Eswatini (SZ)",
  "Ethiopia (ET)",
  "Faroe Islands (FO)",
  "Fiji (FJ)",
  "Finland (FI)",
  "France (FR)",
  "French Guiana (GF)",
  "French Polynesia (PF)",
  "Gabon (GA)",
  "Gambia (GM)",
  "Georgia (GE)",
  "Germany (DE)",
  "Ghana (GH)",
  "Greece (GR)",
  "Grenada (GD)",
  "Guatemala (GT)",
  "Guinea (GN)",
  "Guinea-Bissau (GW)",
  "Guyana (GY)",
  "Haiti (HT)",
  "Honduras (HN)",
  "Hong Kong SAR China (HK)",
  "Hungary (HU)",
  "Iceland (IS)",
  "India (IN)",
  "Indonesia (ID)",
  "Iran (IR)",
  "Iraq (IQ)",
  "Ireland (IE)",
  "Israel (IL)",
  "Italy (IT)",
  "Ivory Coast (CI)",
  "Jamaica (JM)",
  "Japan (JP)",
  "Jordan (JO)",
  "Kazakhstan (KZ)",
  "Kenya (KE)",
  "Kiribati (KI)",
  "Korea (North) (KP)",
  "Korea (South) (KR)",
  "Kuwait (KW)",
  "Kyrgyzstan (KG)",
  "Laos (LA)",
  "Latvia (LV)",
  "Lebanon (LB)",
  "Lesotho (LS)",
  "Liberia (LR)",
  "Libya (LY)",
  "Liechtenstein (LI)",
  "Lithuania (LT)",
  "Luxembourg (LU)",
  "Madagascar (MG)",
  "Malawi (MW)",
  "Malaysia (MY)",
  "Maldives (MV)",
  "Mali (ML)",
  "Malta (MT)",
  "Marshall Islands (MH)",
  "Mauritania (MR)",
  "Mauritius (MU)",
  "Mexico (MX)",
  "Micronesia (FM)",
  "Moldova (MD)",
  "Monaco (MC)",
  "Mongolia (MN)",
  "Montenegro (ME)",
  "Morocco (MA)",
  "Mozambique (MZ)",
  "Myanmar (MM)",
  "Namibia (NA)",
  "Nauru (NR)",
  "Nepal (NP)",
  "Netherlands (NL)",
  "New Zealand (NZ)",
  "Nicaragua (NI)",
  "Niger (NE)",
  "Nigeria (NG)",
  "North Macedonia (MK)",
  "Norway (NO)",
  "Oman (OM)",
  "Pakistan (PK)",
  "Palau (PW)",
  "Palestinian Territories (PS)",
  "Panama (PA)",
  "Papua New Guinea (PG)",
  "Paraguay (PY)",
  "Peru (PE)",
  "Philippines (PH)",
  "Poland (PL)",
  "Portugal (PT)",
  "Puerto Rico (PR)",
  "Qatar (QA)",
  "Romania (RO)",
  "Russia (RU)",
  "Rwanda (RW)",
  "Saint Kitts and Nevis (KN)",
  "Saint Lucia (LC)",
  "Saint Vincent and the Grenadines (VC)",
  "Samoa (WS)",
  "San Marino (SM)",
  "Sao Tome and Principe (ST)",
  "Saudi Arabia (SA)",
  "Senegal (SN)",
  "Serbia (RS)",
  "Seychelles (SC)",
  "Sierra Leone (SL)",
  "Singapore (SG)",
  "Slovakia (SK)",
  "Slovenia (SI)",
  "Solomon Islands (SB)",
  "Somalia (SO)",
  "South Africa (ZA)",
  "South Sudan (SS)",
  "Spain (ES)",
  "Svalbard & Jan Mayen (SJ)",
  "Sri Lanka (LK)",
  "Sudan (SD)",
  "Suriname (SR)",
  "Sweden (SE)",
  "Switzerland (CH)",
  "Syria (SY)",
  "Taiwan (TW)",
  "Tajikistan (TJ)",
  "Tanzania (TZ)",
  "Thailand (TH)",
  "Timor-Leste (TL)",
  "Togo (TG)",
  "Tonga (TO)",
  "Trinidad and Tobago (TT)",
  "Tunisia (TN)",
  "Turkey (TR)",
  "Turkmenistan (TM)",
  "Tuvalu (TV)",
  "Uganda (UG)",
  "Ukraine (UA)",
  "United Arab Emirates (AE)",
  "United Kingdom (GB)",
  "United States (US)",
  "Uruguay (UY)",
  "Uzbekistan (UZ)",
  "Vanuatu (VU)",
  "Vatican City (VA)",
  "Venezuela (VE)",
  "Vietnam (VN)",
  "Yemen (YE)",
  "Zambia (ZM)",
  "Zimbabwe (ZW)",
];

export const internationalLanguages = [
  "Mandarin Chinese",
  "English",
  "Hindi",
  "Spanish",
  "French",
  "Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Indonesian",
  "German",
  "Japanese",
  "Swahili",
  "Turkish",
  "Korean",
  "Vietnamese",
  "Tamil",
  "Urdu",
  "Italian",
  "Polish",
  "Persian",
  "Dutch",
  "Thai",
  "Greek",
  "Czech",
  "Hungarian",
  "Finnish",
  "Danish",
  "Swedish",
  "Hebrew",
  "Malay",
  "Filipino",
  "Norwegian",
  "Ukrainian",
  "Romanian",
  "Zulu",
  "Afrikaans",
  "Serbian",
  "Kazakh",
  "Pashto",
  "Punjabi",
  "Amharic",
  "Somali",
  "Burmese",
  "Nepali",
  "Sinhala",
  "Tagalog",
  "Khmer",
  "Lao",
  "Hausa",
  "Igbo",
  "Yoruba",
  "Haitian Creole"
];
